
const FOOD_DATASET = [
  // --- PIZZAS ---
  {
    id: "FH-101",
    name: "Margherita Supreme Pizza",
    category: "Pizza",
    cuisine: "Italian",
    description: "Classic Neapolitan crust topped with vine-ripened San Marzano tomato sauce, fresh mozzarella cheese, and sweet basil leaves.",
    price: 13.99,
    rating: 4.8,
    reviews: 1420,
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },
  {
    id: "FH-102",
    name: "Pepperoni Passion Pizza",
    category: "Pizza",
    cuisine: "Italian",
    description: "Loaded with double spicy pepperoni, extra mozzarella cheese, and garlic herb infused tomato base.",
    price: 16.49,
    rating: 4.9,
    reviews: 2150,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 20,
    offerPercentage: 20,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },
  {
    id: "FH-103",
    name: "BBQ Smoked Chicken Pizza",
    category: "Pizza",
    cuisine: "American",
    description: "Tender grilled BBQ chicken, red onions, smoked bacon, cilantro, and tangy barbecue sauce base.",
    price: 17.99,
    rating: 4.7,
    reviews: 980,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 10,
    offerPercentage: 10,
    time: "25-30 min",
    preparationTime: "25-30 min"
  },
  {
    id: "FH-104",
    name: "Quattro Formaggi (4-Cheese)",
    category: "Pizza",
    cuisine: "Italian",
    description: "Rich blend of mozzarella, gorgonzola, parmesan, and fontina cheeses with white garlic cream base.",
    price: 15.99,
    rating: 4.6,
    reviews: 640,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: false,
    isPopular: false,
    offer: 0,
    offerPercentage: 0,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },
  {
    id: "FH-105",
    name: "Farmhouse Veggie Feast Pizza",
    category: "Pizza",
    cuisine: "Italian",
    description: "Crispy bell peppers, sweetcorn, mushrooms, red onions, black olives, and juicy tomatoes.",
    price: 14.50,
    rating: 4.7,
    reviews: 1120,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },
  {
    id: "FH-106",
    name: "Mexican Fiery Jalapeño Pizza",
    category: "Pizza",
    cuisine: "Mexican",
    description: "Spicy jalapeños, ground beef, bell peppers, chipotle cream sauce, and melted cheddar cheese.",
    price: 16.99,
    rating: 4.8,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 20,
    offerPercentage: 20,
    time: "25-30 min",
    preparationTime: "25-30 min"
  },

  // --- BURGERS ---
  {
    id: "FH-107",
    name: "Classic Cheese Smash Burger",
    category: "Burger",
    cuisine: "American",
    description: "100% Angus beef patty smashed crispy with melted American cheese, lettuce, pickles, and house sauce.",
    price: 10.99,
    rating: 4.9,
    reviews: 3200,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 10,
    offerPercentage: 10,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },
  {
    id: "FH-108",
    name: "Double Bacon Avocado Burger",
    category: "Burger",
    cuisine: "American",
    description: "Two grilled beef patties, crispy smoked bacon, ripe sliced avocado, gouda cheese, and garlic aioli.",
    price: 14.99,
    rating: 4.8,
    reviews: 1850,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },
  {
    id: "FH-109",
    name: "Crispy Spicy Zinger Burger",
    category: "Burger",
    cuisine: "American",
    description: "Extra crunchy fried chicken breast fillet seasoned in fiery spices with cabbage slaw and sriracha mayo.",
    price: 11.49,
    rating: 4.7,
    reviews: 2400,
    image: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 20,
    offerPercentage: 20,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },
  {
    id: "FH-110",
    name: "Gourmet Mushroom Swiss Burger",
    category: "Burger",
    cuisine: "American",
    description: "Sautéed wild portobello mushrooms, melted Swiss cheese, caramelized onions, and truffle mayonnaise.",
    price: 13.99,
    rating: 4.6,
    reviews: 740,
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: false,
    isPopular: false,
    offer: 0,
    offerPercentage: 0,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },
  {
    id: "FH-111",
    name: "Crispy Black Bean Veggie Burger",
    category: "Burger",
    cuisine: "American",
    description: "Homemade black bean and sweetcorn patty with grilled avocado, tomato, arugula, and vegan herb mayo.",
    price: 9.99,
    rating: 4.5,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 10,
    offerPercentage: 10,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },

  // --- BIRYANI ---
  {
    id: "FH-112",
    name: "Hyderabadi Dum Chicken Biryani",
    category: "Biryani",
    cuisine: "Indian",
    description: "Authentic long-grain basmati rice cooked dum style with marinated tender chicken pieces, saffron, and aromatic spices.",
    price: 15.99,
    rating: 4.9,
    reviews: 4100,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 20,
    offerPercentage: 20,
    time: "25-30 min",
    preparationTime: "25-30 min"
  },
  {
    id: "FH-113",
    name: "Royal Lucknowi Mutton Biryani",
    category: "Biryani",
    cuisine: "Indian",
    description: "Mouth-watering tender mutton chunks slow-cooked with basmati rice, kewra water, fried onions, and ghee.",
    price: 18.99,
    rating: 4.9,
    reviews: 2900,
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "30-35 min",
    preparationTime: "30-35 min"
  },
  {
    id: "FH-114",
    name: "Paneer Tikka Dum Biryani",
    category: "Biryani",
    cuisine: "Indian",
    description: "Tandoori grilled cottage cheese cubes layered with spiced basmati rice, mint raita, and fried cashews.",
    price: 13.99,
    rating: 4.7,
    reviews: 1450,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 10,
    offerPercentage: 10,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },
  {
    id: "FH-115",
    name: "Special Veg Handi Biryani",
    category: "Biryani",
    cuisine: "Indian",
    description: "Assorted seasonal vegetables simmered with basmati rice, green cardamom, and fresh coriander in a clay handi.",
    price: 11.99,
    rating: 4.6,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: false,
    isPopular: false,
    offer: 0,
    offerPercentage: 0,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },

  // --- NORTH INDIAN ---
  {
    id: "FH-116",
    name: "Butter Chicken (Murgh Makhani)",
    category: "North Indian",
    cuisine: "Indian",
    description: "Tender tandoori chicken simmered in a silky, buttery tomato cream gravy infused with kasuri methi.",
    price: 14.99,
    rating: 4.9,
    reviews: 5200,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },
  {
    id: "FH-117",
    name: "Paneer Butter Masala",
    category: "North Indian",
    cuisine: "Indian",
    description: "Soft cottage cheese cubes cooked in rich cashew tomato gravy seasoned with aromatic garam masala.",
    price: 12.99,
    rating: 4.8,
    reviews: 3100,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 10,
    offerPercentage: 10,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },
  {
    id: "FH-118",
    name: "Dal Makhani & Butter Naan Combo",
    category: "North Indian",
    cuisine: "Indian",
    description: "Slow-cooked black lentils overnight with butter and cream, served alongside hot garlic butter naan.",
    price: 11.49,
    rating: 4.9,
    reviews: 2750,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 20,
    offerPercentage: 20,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },

  // --- SOUTH INDIAN ---
  {
    id: "FH-119",
    name: "Crispy Masala Dosa",
    category: "South Indian",
    cuisine: "Indian",
    description: "Golden crispy fermented rice crepe stuffed with spiced potato masala, served with coconut chutney and sambar.",
    price: 8.99,
    rating: 4.8,
    reviews: 2600,
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },

  // --- CHINESE ---
  {
    id: "FH-120",
    name: "Schezwan Hakka Noodles",
    category: "Chinese",
    cuisine: "Chinese",
    description: "Stir-fried noodles with crunchy carrots, cabbage, bell peppers tossed in spicy Schezwan sauce.",
    price: 10.49,
    rating: 4.7,
    reviews: 1840,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },
  {
    id: "FH-121",
    name: "Crispy Chilli Chicken",
    category: "Chinese",
    cuisine: "Chinese",
    description: "Deep-fried boneless chicken nuggets tossed in dark soy sauce, green chilies, garlic, and spring onions.",
    price: 12.99,
    rating: 4.8,
    reviews: 2200,
    image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 10,
    offerPercentage: 10,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },

  // --- ITALIAN & PASTA ---
  {
    id: "FH-122",
    name: "Creamy Alfredo Fettuccine Pasta",
    category: "Pasta",
    cuisine: "Italian",
    description: "Fettuccine pasta smothered in parmesan garlic cream sauce with sautéed wild mushrooms.",
    price: 13.99,
    rating: 4.8,
    reviews: 1420,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281270?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 15,
    offerPercentage: 15,
    time: "20-25 min",
    preparationTime: "20-25 min"
  },

  // --- MEXICAN ---
  {
    id: "FH-123",
    name: "Loaded Grilled Beef Tacos (3 Pcs)",
    category: "Mexican",
    cuisine: "Mexican",
    description: "Soft corn tortillas stuffed with seasoned grilled beef steak, pico de gallo salsa, guacamole, and queso.",
    price: 12.99,
    rating: 4.9,
    reviews: 2100,
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
    veg: false,
    isVeg: false,
    popular: true,
    isPopular: true,
    offer: 20,
    offerPercentage: 20,
    time: "15-20 min",
    preparationTime: "15-20 min"
  },

  // --- DESSERTS ---
  {
    id: "FH-124",
    name: "Classic Chocolate Lava Cake",
    category: "Desserts",
    cuisine: "American",
    description: "Warm chocolate cake with molten fudge center, served with a scoop of Madagascar vanilla bean ice cream.",
    price: 7.99,
    rating: 4.9,
    reviews: 3800,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    veg: true,
    isVeg: true,
    popular: true,
    isPopular: true,
    offer: 20,
    offerPercentage: 20,
    time: "15 min",
    preparationTime: "15 min"
  }
];

// Dynamically populate up to 100 complete items
(function generateRemainingItems() {
  const baseCategories = ["Pizza", "Burger", "Biryani", "Chinese", "North Indian", "South Indian", "Italian", "Mexican", "Desserts", "Drinks", "Fast Food", "Healthy", "Sea Food", "Breakfast", "Street Food", "Pasta", "Sandwich", "Rolls"];
  const baseCuisines = ["Indian", "Italian", "Chinese", "American", "Mexican", "Thai", "Japanese"];
  const images = [
    "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80",
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80",
    "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
    "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
    "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
    "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80"
  ];

  for (let i = 125; i <= 200; i++) {
    const catIndex = (i - 125) % baseCategories.length;
    const cat = baseCategories[catIndex];
    const cuisine = baseCuisines[i % baseCuisines.length];
    const isVeg = i % 2 === 0;
    const isPopular = i % 3 === 0;
    const price = parseFloat((7.99 + ((i % 15) * 1.1)).toFixed(2));
    const rating = parseFloat((4.2 + ((i % 8) * 0.1)).toFixed(1));
    const reviews = 150 + (i * 18);
    const offerVal = (i % 4) * 5;
    const timeVal = `${15 + (i % 15)} min`;

    FOOD_DATASET.push({
      id: `FH-${i}`,
      name: `Special ${cat} Feast #${i - 124}`,
      category: cat,
      cuisine: cuisine,
      description: `Chef special ${cat.toLowerCase()} prepared freshly with authentic ${cuisine.toLowerCase()} herbs, spices, and premium ingredients.`,
      price: price,
      rating: rating,
      reviews: reviews,
      image: images[i % images.length],
      veg: isVeg,
      isVeg: isVeg,
      popular: isPopular,
      isPopular: isPopular,
      offer: offerVal,
      offerPercentage: offerVal,
      time: timeVal,
      preparationTime: timeVal
    });
  }
})();

window.FOOD_DATASET = FOOD_DATASET;
